# version: "2.4"
services:
  jenkins:
    # depends_on:
    #   artifactory:
    #     condition: service_healthy
    build: jenkins_controller
    container_name: jenkins
    ports:
      - "50000:50000"
      - "8880:8080"
    volumes:
      - ./jenkins_controller/jenkins.yaml:/usr/share/jenkins/ref/jenkins.yaml
    restart: always

  jenkins-agent:
    depends_on:
      - jenkins
    container_name: jenkins_agent
    build: jenkins_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2222:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaJxXl+C4GsmIcrsXQ+mqS/t9SNsFrtj5LffdnNr8+9a40UUHDX1mKe26U8oSarCciLYEtXWsWtl1VmQS6JAdVI5vZKS2J0Nt6oe+AH9y2PhL6wtqUsel2aJHUk8w13Dfkt+w6tZBQxCuzBDvWRt6hsprVuJvWoICMZanVOoXb+BfJx9133mG/uviF/rgtEqn5CqTbHWN1cUs+jei0GOlfyQr/GR7P5cP6baxe5yxCebohlgbYvDrwUT2ZBSlJHIaqbrbeBF/yigCcWCA9z46PubKc/qIcDY5qeFuldy0mqEdpMILDLjcrtidnp4wvRa8cxZl4w9fNYGwK8C56/b9n
    restart: always

  sonarqube:
    image: sonarqube:10.2.1-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: always

  # artifactory:
  #   image: docker.bintray.io/jfrog/artifactory-jcr:7.39.4
  #   container_name: artifactory
  #   ports:
  #     - "8081:8081"
  #     - "8082:8082"
  #   volumes:
  #     - ./artifactory:/artifactory_extra_conf
  #   restart: always
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8082/artifactory/api/system/ping"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 30
  #     start_period: 180s
