services:
  jenkins:
    build: jenkins_controller
    container_name: jenkins
    restart: always
    volumes: 
      - ./jenkins_controller/jenkins.yml:/user/share/jenkins/ref/jenkins.yml
    ports:
      - 8880:8080
      - 50000:50000
  sonarqube:
    image: sonarqube:10.2.1-community
    container_name: sonarqube
    restart: always
    ports:
      - 9000:9000